services:
  - type: web
    name: lexfiat
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist/public
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_CYRANO_API_URL
        value: https://cyrano-mcp-server.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

