services:
  - type: web
    name: lexfiat
    env: static
  buildCommand: cd client && rm -rf node_modules dist .vite package-lock.json && npm ci && npm run build && mv dist ../dist
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_CYRANO_API_URL
        value: https://cyrano-mcp-server.onrender.com
      - key: BUILD_CACHE_BUST
        value: "20251007-v2"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

